---
version: 3
dependencies:
  ansible_core:
    package_pip: ansible==7.4.0
    # package_pip: ansible-core==2.14.5
  ansible_runner:
    package_pip: ansible-runner==2.3.2
  # galaxy: requirements.yml
  # galaxy:
  #   collections:
  #     - cisco.ios
  #     - cisco.iosxr
  #     - cisco.nxos
  #     - junipernetworks.junos
  # python: requirements.txt
  python:
    - ntc-templates==3.3.0
    - jmespath==1.0.1
    - ansible-pylibssh==1.1.0
  # python_interpreter:
  #   package_system: "python310"
  #   python_path: "/usr/bin/python3.10"
  # system: bindep.txt

images:
  base_image:
    name: quay.io/centos/centos:stream9

  # prepend_final: |
  #   RUN whoami
  #   RUN cat /etc/os-release
  # append_final:
  #   - RUN echo This is a post-install command!
  #   - RUN ls -la /etc